import type { ActionPair } from "@/types/prompt";

export const ACTION_PAIRS: ActionPair[] = [
  { citizenAction: "먹는", mafiaAction: "마시는", allowedCategories: ["동물", "사람", "직업", "음식"] },
  { citizenAction: "달리는", mafiaAction: "점프하는", allowedCategories: ["동물", "사람", "직업", "스포츠"] },
  { citizenAction: "우는", mafiaAction: "화난", allowedCategories: ["동물", "사람"] },
  { citizenAction: "웃는", mafiaAction: "노래하는", allowedCategories: ["동물", "사람", "직업"] },
  { citizenAction: "쓰는", mafiaAction: "그리는", allowedCategories: ["사람", "직업", "학용품"] },
  { citizenAction: "읽는", mafiaAction: "넘기는", allowedCategories: ["사람", "직업", "학용품"] },
  { citizenAction: "자는", mafiaAction: "하품하는", allowedCategories: ["동물", "사람"] },
  { citizenAction: "청소하는", mafiaAction: "닦는", allowedCategories: ["사람", "직업", "장소", "물건"] },
  { citizenAction: "요리하는", mafiaAction: "굽는", allowedCategories: ["사람", "직업", "음식"] },
  { citizenAction: "운전하는", mafiaAction: "타는", allowedCategories: ["사람", "직업", "탈것"] },
  { citizenAction: "공 차는", mafiaAction: "드리블하는", allowedCategories: ["사람", "직업", "스포츠"] },
  { citizenAction: "수영하는", mafiaAction: "잠수하는", allowedCategories: ["동물", "사람", "직업", "자연"] },

  { citizenAction: "걷는", mafiaAction: "뛰어가는", allowedCategories: ["동물", "사람", "직업"] },
  { citizenAction: "앉아있는", mafiaAction: "무릎 꿇은", allowedCategories: ["동물", "사람", "직업"] },
  { citizenAction: "손드는", mafiaAction: "박수치는", allowedCategories: ["사람", "직업"] },
  { citizenAction: "이야기하는", mafiaAction: "속삭이는", allowedCategories: ["사람", "직업"] },
  { citizenAction: "전화하는", mafiaAction: "문자하는", allowedCategories: ["사람", "직업", "물건"] },
  { citizenAction: "가리키는", mafiaAction: "살펴보는", allowedCategories: ["사람", "직업", "동물", "물건", "장소"] },
  { citizenAction: "들고 가는", mafiaAction: "끌고 가는", allowedCategories: ["사람", "직업", "물건", "학용품", "음식"] },
  { citizenAction: "여는", mafiaAction: "닫는", allowedCategories: ["사람", "직업", "물건", "장소", "학용품"] },
  { citizenAction: "밀는", mafiaAction: "당기는", allowedCategories: ["사람", "직업", "물건", "탈것"] },
  { citizenAction: "던지는", mafiaAction: "받는", allowedCategories: ["사람", "직업", "스포츠", "물건"] },
  { citizenAction: "붙이는", mafiaAction: "떼는", allowedCategories: ["사람", "직업", "학용품", "물건"] },
  { citizenAction: "자르는", mafiaAction: "오리는", allowedCategories: ["사람", "직업", "음식", "학용품"] },
  { citizenAction: "씻는", mafiaAction: "헹구는", allowedCategories: ["사람", "직업", "동물", "물건", "음식"] },
  { citizenAction: "양치하는", mafiaAction: "입 헹구는", allowedCategories: ["사람", "직업"] },
  { citizenAction: "사진 찍는", mafiaAction: "촬영하는", allowedCategories: ["사람", "직업", "동물", "장소"] },
  { citizenAction: "연주하는", mafiaAction: "노래하는", allowedCategories: ["사람", "직업"] },
  { citizenAction: "춤추는", mafiaAction: "빙글도는", allowedCategories: ["사람", "직업", "동물"] },
  { citizenAction: "기어가는", mafiaAction: "미끄러지는", allowedCategories: ["동물", "사람", "스포츠"] },
  { citizenAction: "심는", mafiaAction: "물 주는", allowedCategories: ["사람", "직업", "자연"] },
  { citizenAction: "낚시하는", mafiaAction: "그물 던지는", allowedCategories: ["사람", "직업", "자연"] },
];
